### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by MrkarlosM** [alexisbec/Smashing-Magazine-Clone#2]
This issue is to give some advice from the 161 group - the palms.

**Comment by MrkarlosM** [comment]
For the search bar try to use padding for the input part. Create the left padding so the Search Icon fits in the padding part. Something like:

```
.search-bar {
  padding: 5px 5px 5px 20px;
}
```

**Comment by abongsjoel** [comment]
It's a good practice to always include the reset CSS file. Meyer's web has a pretty good one, you can find it here: https://meyerweb.com/eric/tools/css/reset/

**Comment by abongsjoel** [comment]
CSS line 3, font-family should always end with a generic font family like serif or sans-serif e.g.
```
font-family: 'Concert One', cursive, serif;
```
